# DataSource properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tableinheritancepostgresqlv3
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none # You can set this to 'update' or 'create-drop' for development, 'none' for production
      jdbc:
        batch_size: 50
      order_inserts: true
      order_updates: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true # Format SQL queries for easier debugging

# Flyway properties
flyway:
  enabled: true
  locations: classpath:db/migration # Location of your SQL migration scripts
  baseline-on-migrate: true # Baseline when running migration for the first time